name: code_of_the_semaphore
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#1B9AAA"
  adaptive_icon_foreground: "assets/icon/icon.png"
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#1B9AAA"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48 
  macos:
    generate: true
    image_path: "assets/icon/icon.png"


flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Beige
      fonts:
        - asset: assets/fonts/Beige_Come.ttf
